CREATE TABLE IF NOT EXISTS apps (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    app_code VARCHAR(32) NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL,
    app_key VARCHAR(64) NOT NULL UNIQUE,
    app_secret VARCHAR(96) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    scenario JSON NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS im_users (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    app_id BIGINT UNSIGNED NOT NULL,
    external_user_id VARCHAR(64) NOT NULL,
    nickname VARCHAR(64) NOT NULL DEFAULT '',
    avatar_url VARCHAR(255) NOT NULL DEFAULT '',
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_app_user (app_id, external_user_id)
);

CREATE TABLE IF NOT EXISTS conversations (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    conversation_no VARCHAR(32) NOT NULL UNIQUE,
    app_id BIGINT UNSIGNED NOT NULL,
    type VARCHAR(32) NOT NULL,
    subject VARCHAR(128) NOT NULL DEFAULT '',
    owner_user_id VARCHAR(64) NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_app_type (app_id, type)
);

CREATE TABLE IF NOT EXISTS messages (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    message_no VARCHAR(32) NOT NULL UNIQUE,
    app_id BIGINT UNSIGNED NOT NULL,
    conversation_id BIGINT UNSIGNED NOT NULL,
    sender_user_id VARCHAR(64) NOT NULL,
    message_type VARCHAR(32) NOT NULL,
    client_msg_id VARCHAR(64) NOT NULL DEFAULT '',
    content JSON NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_conv_created (conversation_id, created_at),
    KEY idx_app_client_msg (app_id, client_msg_id)
);
