ALTER TABLE conversation_members
ADD COLUMN status VARCHAR(32) NOT NULL DEFAULT 'active' COMMENT '成员状态' AFTER role,
ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间' AFTER created_at;
