ALTER TABLE conversation_members
ADD COLUMN status VARCHAR(32) NOT NULL DEFAULT 'active' AFTER role,
ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;
